[package]
name = "rabbit"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"

[dependencies]
# For logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
jiff = "0.2"

# For metrics
opentelemetry = { version = "0.32", default-features = false, features = ["metrics"] }
opentelemetry_sdk = { version = "0.32", default-features = false, features = ["metrics"] }

# For error propagation
eros = "0.7"

# For config
config = { version = "0.15", default-features = false, features = ["toml"] }
serde = { version = "1.0", features = ["derive"] }
directories = "6.0"

# For static IOC
kudi = "0.1"

# For platform difference
cfg-if = "1.0"

# For async runtime
compio = "0.19"
flume = { version = "0.12", default-features = false, features = ["async"] }

# For UI
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = [
  "font-kit",
  "wayland",
] }
gpui-component = { git = "https://github.com/longbridge/gpui-component" }

[features]
default = []
fake = []
test-ui = []
