#!/bin/sh

set -eu

cargo test \
    --color=always \
    --lib \
    infra::platform::video_encoder::gstreamer:: \
    -- \
    --ignored \
    --nocapture

exec cargo test \
    --color=always \
    --lib \
    infra::platform::video_decoder:: \
    -- \
    --ignored \
    --nocapture
